name: cd

on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed

jobs:
  start:
    runs-on: be-cyber_community

    steps:
      - name: Chạy lần đầu
        run: sudo docker compose up -d
