name: ci

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Đăng nhập docker hub
        run: docker login -u minhhuy2410 -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build image
        run: docker build -t minhhuy2410/img-be_cyber_community:latest .

      - name: Push image lên docker hub
        run: docker push minhhuy2410/img-be_cyber_community:latest
